---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'VM and EBS Bock stack
Parameters:
  KeyName:
    Description: Key Pair name
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: mykey
  VPC:
    Description: 'Just select the one and only default VPC'
    Type: 'AWS::EC2::VPC::Id'
  Subnet:
    Description: 'Just select one of the available subnets'
    Type: 'AWS::EC2::Subnet::Id'
Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Allow incoming SSH from anywhere'
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - CidrIp: '0.0.0.0/0'
        FromPort: 22
        ToPort: 22
        IpProtocol: tcp
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-0be2609ba883822ec'
      InstanceType: 't2.micro'
      KeyName: !Ref KeyName
      SecurityGroupIds: [!Ref SecurityGroup]
      SubnetId: !Ref Subnet
  Volume:
    Type: 'AWS::EC2::Volume'
    Properties:
      AvailabilityZone: !Sub ${EC2Instance.AvailabilityZone}
      Size: 5
      VolumeType: gp2
  VolumeAttachment:
    Type: 'AWS::EC2::VolumeAttachment'
    Properties:
      Device: '/dev/xvdf'
      InstanceId: !Ref EC2Instance
      VolumeId: !Ref Volume
Outputs:
  PublicName:
    Value: !Sub ${EC2Instance.PublicDnsName}
    Description: 'Public name (connect via SSH as user ec2-user)'
  VolumeId:
    Value: !Ref Volume
    Description: 'ID of the EBS volume'
